; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[common]
platform = espressif32
board = esp32-s2-saola-1
framework = arduino
board_upload.flash_size = 8MB
board_upload.maximum_size = 8388608
lib_deps = 
	marvinroger/AsyncMqttClient@^0.9.0
	bblanchon/ArduinoJson@^7.3.0
    adafruit/Adafruit NeoPixel@^1.12.5    
build_flags = 
	-DBOARD_HAS_PSRAM
	-mfix-esp32-psram-cache-issue

[env:krvkplant]
extends = common
monitor_speed = 115200

[env:krvkplant_ota]
extends = common
upload_protocol = espota
upload_port = krvkplant.local